=== dret/I-D/Abandoned/home-xml/draft-wilde-home-xml-05-files/home-xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="urn:ietf:params:xml:ns:homedoc" elementFormDefault="qualified" xmlns:home="urn:ietf:params:xml:ns:homedoc">
 <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
 <xs:element name="resources">
  <xs:complexType>
   <xs:sequence maxOccurs="unbounded" minOccurs="0">
    <xs:element name="resource">
     <xs:complexType>
      <xs:sequence>
       <xs:choice>
        <xs:element name="link">
         <xs:complexType>
          <xs:attribute name="href" type="xs:anyURI" use="required"/>
         </xs:complexType>
        </xs:element>
        <xs:element name="template">
         <xs:complexType>
          <xs:sequence maxOccurs="unbounded" minOccurs="0">
           <xs:element name="var">
            <xs:complexType>
             <xs:attribute name="name" use="required"/>
             <xs:attribute name="URI" type="xs:anyURI" use="required"/>
            </xs:complexType>
           </xs:element>
          </xs:sequence>
          <xs:attribute name="href-template" use="required"/>
         </xs:complexType>
        </xs:element>
       </xs:choice>
       <xs:element minOccurs="0" name="hints">
        <xs:complexType>
         <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element name="allow" type="home:arrayType"/>
          <xs:element name="formats">
           <xs:complexType>
            <xs:sequence>
             <xs:element name="format">
              <xs:complexType>
               <xs:attribute name="mediatype" type="home:mediaTypeType"/>
              </xs:complexType>
             </xs:element>
            </xs:sequence>
           </xs:complexType>
          </xs:element>
          <xs:element name="accept-patch" type="home:mediaTypeArrayType"/>
          <xs:element name="accept-post" type="home:mediaTypeArrayType"/>
          <xs:element name="accept-ranges" type="home:arrayType"/>
          <xs:element name="accept-prefer" type="home:arrayType"/>
          <xs:element name="docs" type="xs:anyURI"/>
          <xs:element name="precondition-req" type="home:arrayType"/>
          <xs:element name="auth-req">
           <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
             <xs:element name="scheme">
              <xs:complexType>
               <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="realm"/>
               </xs:sequence>
               <xs:attribute name="name" type="xs:token"/>
              </xs:complexType>
             </xs:element>
            </xs:sequence>
           </xs:complexType>
          </xs:element>
          <xs:element name="status">
           <xs:simpleType>
            <xs:restriction base="xs:token">
             <xs:enumeration value="deprecated"/>
             <xs:enumeration value="gone"/>
            </xs:restriction>
           </xs:simpleType>
          </xs:element>
         </xs:choice>
        </xs:complexType>
       </xs:element>
      </xs:sequence>
      <xs:attribute name="rel" type="xs:anyURI" use="required"/>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
   <xs:attribute ref="xml:base" use="optional"/>
  </xs:complexType>
 </xs:element>
 <xs:simpleType name="mediaTypeType">
  <xs:restriction base="xs:string"/>
 </xs:simpleType>
 <xs:complexType name="arrayType">
  <xs:sequence maxOccurs="unbounded" minOccurs="0">
   <xs:element name="i"/>
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="mediaTypeArrayType">
  <xs:sequence maxOccurs="unbounded" minOccurs="0">
   <xs:element name="i" type="home:mediaTypeType"/>
  </xs:sequence>
 </xs:complexType>
</xs:schema>

=== dret/I-D/Abandoned/home-xml/draft-wilde-home-xml-04-files/home-xml.xml
<?xml-stylesheet type="text/xsl" href="home-xml-02.xslt"?>
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:ietf:params:xml:ns:homedoc home-xml.xsd"
 xmlns="urn:ietf:params:xml:ns:homedoc" xml:base="tag:me@example.com,2016:">
 <resource rel="http://example.org/rel/widgets">
  <link href="/widgets"/>
 </resource>
 <resource rel="widgets">
  <template href-template="/widgets/{widget_id}">
   <var name="widget_id" URI="widget"/>
  </template>
  <hints>
   <allow>
    <i>GET</i>
    <i>PUT</i>
    <i>DELETE</i>
    <i>PATCH</i>
   </allow>
   <formats>
    <format mediatype="application/json"/>
   </formats>
   <accept-patch>
    <i>application/json-patch+json</i>
   </accept-patch>
   <accept-post>
    <i>application/xml</i>
   </accept-post>
   <accept-ranges>
    <i>bytes</i>
   </accept-ranges>
  </hints>
 </resource>
</resources>
