=== dret/I-D/template-desc/td-00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="urn:ietf:rfc:9999" xmlns:td="urn:ietf:rfc:9999">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd">
        <xs:annotation>
            <xs:documentation>Get access to the xml: attribute groups for xml:lang as declared on 'documentation' below.</xs:documentation>
        </xs:annotation>
    </xs:import>
    <xs:element name="td">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="variable">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="restriction" minOccurs="0">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="minExclusive" type="td:facet"/>
                                        <xs:element name="minInclusive" type="td:facet"/>
                                        <xs:element name="maxExclusive" type="td:facet"/>
                                        <xs:element name="maxInclusive" type="td:facet"/>
                                        <xs:element name="totalDigits">
                                            <xs:complexType>
                                                <xs:complexContent>
                                                  <xs:restriction base="td:numFacet">
                                                  <xs:attribute name="value"
                                                  type="xs:positiveInteger" use="required"/>
                                                  </xs:restriction>
                                                </xs:complexContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="fractionDigits" type="td:numFacet"/>
                                        <xs:element name="length" type="td:numFacet"/>
                                        <xs:element name="minLength" type="td:numFacet"/>
                                        <xs:element name="maxLength" type="td:numFacet"/>
                                        <xs:element name="enumeration" type="td:facet"/>
                                        <xs:element name="whiteSpace">
                                            <xs:complexType>
                                                <xs:complexContent>
                                                  <xs:restriction base="td:facet">
                                                  <xs:attribute name="value" use="required">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:NMTOKEN">
                                                  <xs:enumeration value="preserve"/>
                                                  <xs:enumeration value="replace"/>
                                                  <xs:enumeration value="collapse"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>
                                                  </xs:restriction>
                                                </xs:complexContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="pattern" type="td:facet"/>
                                    </xs:choice>
                                    <xs:attribute name="base" use="required">
                                        <xs:simpleType>
                                            <xs:union memberTypes="xs:NCName xs:QName"/>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                                <xs:element name="appinfo" id="appinfo">
                                    <xs:complexType mixed="true">
                                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                            <xs:any processContents="lax"/>
                                        </xs:sequence>
                                        <xs:attribute name="source" type="xs:anyURI"/>
                                        <xs:anyAttribute namespace="##other" processContents="lax"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="documentation" id="documentation">
                                    <xs:complexType mixed="true">
                                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                            <xs:any processContents="lax"/>
                                        </xs:sequence>
                                        <xs:attribute name="source" type="xs:anyURI"/>
                                        <xs:attribute ref="xml:lang"/>
                                        <xs:anyAttribute namespace="##other" processContents="lax"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="name" use="required"/>
                        <xs:attribute name="concept-uri" type="xs:anyURI" use="optional"/>
                        <xs:attribute name="concept-qname" type="xs:QName" use="optional"/>
<!--
                        <xs:assert test="count((@concept-uri, @concept-qname)) le 1"/>
-->
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="hreft" type="td:uriTemplate"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="uriTemplate">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <!-- these are simplified versions of the types for facet elements as defined in the schema for schemas at http://www.w3.org/2001/XMLSchema.xsd -->
    <xs:complexType name="facet">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:attribute name="value" use="required"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="numFacet">
        <xs:complexContent>
            <xs:restriction base="td:facet">
                <xs:attribute name="value" type="xs:nonNegativeInteger" use="required"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== dret/I-D/template-desc/td-paging-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="td-00.xslt"?>
<td xmlns="urn:ietf:rfc:9999" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:rfc:9999 td-00.xsd" hreft="http://www.example.com/feed{?pagesize,page}">
   <variable name="pagesize" concept-uri="http://example.com/feedpaging/pagesize">
      <restriction base="positiveInteger">
         <minInclusive value="5"/>
         <maxInclusive value="100"/>
      </restriction>
      <documentation xml:lang="en">Number of returned items per page.</documentation>
   </variable>
   <variable name="page" concept-uri="http://example.com/feedpaging/page">
      <restriction base="positiveInteger"/>
      <documentation xml:lang="en">Page number of the returned page (based on the requested pagesize or a server-configured default).</documentation>
   </variable>
   <documentation xml:lang="en">Template for accessing a paged feed of entries at http://www.example.com/feed, with client controls for the page size, and the returned page.</documentation>
</td>
